<?php
/**
 * @package Blox Page Builder
 * @author UniteCMS.net
 * @copyright (C) 2017 Unite CMS, All Rights Reserved. 
 * @license GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * */
defined('UNLIMITED_ADDONS_INC') or die('Restricted access');

GlobalsUC::$arrServerSideText = array(
		"uncategorized"=>__("Uncategorized", ADDONLIBRARY_TEXTDOMAIN),
		"all_addons"=>__("All Addons", ADDONLIBRARY_TEXTDOMAIN),
		"new_layout"=>__("New Layout", ADDONLIBRARY_TEXTDOMAIN),
		"import_layout"=>__("Import Layout", ADDONLIBRARY_TEXTDOMAIN),
		"import_layouts"=>__("Import Layouts", ADDONLIBRARY_TEXTDOMAIN),
		"layouts_global_settings"=>__("Layouts Global Settings", ADDONLIBRARY_TEXTDOMAIN),
		"save_layout_settings"=>__("Save Layout Settings", ADDONLIBRARY_TEXTDOMAIN),
		"no_layouts_found"=>__("No Layouts Found", ADDONLIBRARY_TEXTDOMAIN),
		"layout_title"=>__("Layout Title", ADDONLIBRARY_TEXTDOMAIN),
		"edit_layout"=>__("Edit Layout", ADDONLIBRARY_TEXTDOMAIN),
		"back_to_layouts_list"=>__("Back to layouts list", ADDONLIBRARY_TEXTDOMAIN),
		"my_layouts"=>__("My Layouts", ADDONLIBRARY_TEXTDOMAIN),
		"layout_deleted"=>__("Layout Deleted", ADDONLIBRARY_TEXTDOMAIN),
		"layout_duplicated"=>__("Layout Duplicated", ADDONLIBRARY_TEXTDOMAIN),
		"all_layouts"=>__("All Layouts", ADDONLIBRARY_TEXTDOMAIN),
		"layouts_added_successfully"=>__("Layouts Added Successfully", ADDONLIBRARY_TEXTDOMAIN),
		"uploading_layouts_file"=>__("Uploading Layouts file...", ADDONLIBRARY_TEXTDOMAIN),
		"layout_created"=>__("Layout Created", ADDONLIBRARY_TEXTDOMAIN),
		"layout_updated"=>__("Layout Updated", ADDONLIBRARY_TEXTDOMAIN),
		"layout_imported"=>__("Layout Imported", ADDONLIBRARY_TEXTDOMAIN),
		"layout_saved"=>__("Layout Saved", ADDONLIBRARY_TEXTDOMAIN),
		"preview_layout"=>__("Preview Layout", ADDONLIBRARY_TEXTDOMAIN),
		"manage_layout_categories"=>__("Manage Layout Categories", ADDONLIBRARY_TEXTDOMAIN),
		"set_category_to_layout"=>__("Set Category To Layout", ADDONLIBRARY_TEXTDOMAIN),
		"select_layouts_export_file"=>__("Select layouts export file", ADDONLIBRARY_TEXTDOMAIN),
		"are_you_sure_to_delete_this_layout"=>__("Are you sure to delete this layout?", ADDONLIBRARY_TEXTDOMAIN),
		"addon_library"=>__("Addon Library", ADDONLIBRARY_TEXTDOMAIN),
		"search_layout"=>__("Search Layout", ADDONLIBRARY_TEXTDOMAIN),
);


GlobalsUC::$arrClientSideText = array(
		"empty"=>__("Empty", ADDONLIBRARY_TEXTDOMAIN),
		"new"=>__("New", ADDONLIBRARY_TEXTDOMAIN),
		"add_item"=>__("Add Item",ADDONLIBRARY_TEXTDOMAIN),
		"update_item"=>__("Update Item",ADDONLIBRARY_TEXTDOMAIN),
		"edit_item"=>__("Edit Item",ADDONLIBRARY_TEXTDOMAIN),
		"close"=>__("Close",ADDONLIBRARY_TEXTDOMAIN),
		"cancel"=>__("Cancel",ADDONLIBRARY_TEXTDOMAIN),
		"update"=>__("Update",ADDONLIBRARY_TEXTDOMAIN),
		"restore"=>__("Restore",ADDONLIBRARY_TEXTDOMAIN),
		"updating"=>__("Updating...",ADDONLIBRARY_TEXTDOMAIN),
		"restoring"=>__("Restoring...",ADDONLIBRARY_TEXTDOMAIN),
		"import"=>__("Import",ADDONLIBRARY_TEXTDOMAIN),
		"edit"=>__("Edit",ADDONLIBRARY_TEXTDOMAIN),
		"edit_addon"=>__("Edit Addon",ADDONLIBRARY_TEXTDOMAIN),
		"addon_container_settings"=>__("Addon Container Settings",ADDONLIBRARY_TEXTDOMAIN),
		"delete_addon"=>__("Delete Addon",ADDONLIBRARY_TEXTDOMAIN),
		"duplicate_addon"=>__("Duplicate Addon",ADDONLIBRARY_TEXTDOMAIN),
		"updating_categories_order"=>__("Updating Categories Order...",ADDONLIBRARY_TEXTDOMAIN),		
		"set_addon"=>__("Set Addon",ADDONLIBRARY_TEXTDOMAIN),
		"add_addon_to_column"=>__("Add Addon To Column",ADDONLIBRARY_TEXTDOMAIN),
		"removing_addons"=>__("Removing Addons...",ADDONLIBRARY_TEXTDOMAIN),
		"updating_addon_title"=>__("Updating Title...",ADDONLIBRARY_TEXTDOMAIN),
		"duplicating_addons"=>__("Duplicating Addons...",ADDONLIBRARY_TEXTDOMAIN),
		"updating_addons_order"=>__("Updating Addons Order...",ADDONLIBRARY_TEXTDOMAIN),
		"updating_addons"=>__("Updating Addons...",ADDONLIBRARY_TEXTDOMAIN),
		"copying_addons"=>__("Copying Addons...",ADDONLIBRARY_TEXTDOMAIN),
		"moving_addons"=>__("Moving Addons...",ADDONLIBRARY_TEXTDOMAIN),
		"confirm_remove_addons"=>__("Are you sure you want to delete these addons?",ADDONLIBRARY_TEXTDOMAIN),
		"uc_textfield"=>__("Text Field",ADDONLIBRARY_TEXTDOMAIN),
		"uc_textarea"=>__("Text Area",ADDONLIBRARY_TEXTDOMAIN),
		"uc_checkbox"=>__("Checkbox",ADDONLIBRARY_TEXTDOMAIN),
		"uc_dropdown"=>__("Dropdown",ADDONLIBRARY_TEXTDOMAIN),
		"uc_radioboolean"=>__("Radio Boolean",ADDONLIBRARY_TEXTDOMAIN),
		"uc_number"=>__("Number",ADDONLIBRARY_TEXTDOMAIN),
		"uc_colorpicker"=>__("Color Picker",ADDONLIBRARY_TEXTDOMAIN),
		"uc_editor"=>__("Editor",ADDONLIBRARY_TEXTDOMAIN),
		"uc_icon"=>__("Icon Picker",ADDONLIBRARY_TEXTDOMAIN),
		"uc_map"=>__("Google Map Picker",ADDONLIBRARY_TEXTDOMAIN),
		"uc_image"=>__("Image",ADDONLIBRARY_TEXTDOMAIN),
		"uc_mp3"=>__("Audio",ADDONLIBRARY_TEXTDOMAIN),
		"uc_post"=>__("Post",ADDONLIBRARY_TEXTDOMAIN),
		"uc_posts_list"=>__("Posts List",ADDONLIBRARY_TEXTDOMAIN),
		"uc_font_override"=>__("Font Override",ADDONLIBRARY_TEXTDOMAIN),
		"uc_imagebase"=>__("Image Fields",ADDONLIBRARY_TEXTDOMAIN),
		"uc_menu"=>__("Menu",ADDONLIBRARY_TEXTDOMAIN),
		"choose_image"=>__("Choose Image",ADDONLIBRARY_TEXTDOMAIN),
		"choose_audio"=>__("Choose Audio",ADDONLIBRARY_TEXTDOMAIN),
		"edit_file"=>__("Edit File",ADDONLIBRARY_TEXTDOMAIN),
		"save"=>__("Save",ADDONLIBRARY_TEXTDOMAIN),
		"delete_op"=>__("Delete",ADDONLIBRARY_TEXTDOMAIN),
		"duplicate_op"=>__("Duplicate",ADDONLIBRARY_TEXTDOMAIN),
		"bulk"=>__("Bulk",ADDONLIBRARY_TEXTDOMAIN),
		"delete_include"=>__("Delete Include",ADDONLIBRARY_TEXTDOMAIN),
		"add_include"=>__("Add Include",ADDONLIBRARY_TEXTDOMAIN),
		"include_settings"=>__("Include Settings",ADDONLIBRARY_TEXTDOMAIN),
		"always"=>__("Always",ADDONLIBRARY_TEXTDOMAIN),
		"never_include"=>__("Never Include",ADDONLIBRARY_TEXTDOMAIN),
		"not_selected"=>__("Not Selected",ADDONLIBRARY_TEXTDOMAIN),
		"choose_addon"=>__("Choose Addon",ADDONLIBRARY_TEXTDOMAIN),
		"delete_row"=>__("Delete Row",ADDONLIBRARY_TEXTDOMAIN),
		"duplicate_row"=>__("Duplicate Row",ADDONLIBRARY_TEXTDOMAIN),
		"copy_row"=>__("Copy Row",ADDONLIBRARY_TEXTDOMAIN),
		"in_buffer"=>__("In Buffer",ADDONLIBRARY_TEXTDOMAIN),
		"paste_row_before_current"=>__("Paste Row Before Current",ADDONLIBRARY_TEXTDOMAIN),
		"delete_column"=>__("Delete Column",ADDONLIBRARY_TEXTDOMAIN),
		"duplicate_column"=>__("Duplicate Column",ADDONLIBRARY_TEXTDOMAIN),
		"column_settings"=>__("Column Settings",ADDONLIBRARY_TEXTDOMAIN),
		"add_column"=>__("Add Column",ADDONLIBRARY_TEXTDOMAIN),
		"move_row"=>__("Move Row",ADDONLIBRARY_TEXTDOMAIN),
		"move_column"=>__("Move Column",ADDONLIBRARY_TEXTDOMAIN),
		"move_addon"=>__("Move Addon",ADDONLIBRARY_TEXTDOMAIN),
		"settings"=>__("Settings",ADDONLIBRARY_TEXTDOMAIN),
		"row"=>__("Row",ADDONLIBRARY_TEXTDOMAIN),
		"row_layout"=>__("Row Layout", ADDONLIBRARY_TEXTDOMAIN),
		"more_actions"=>__("More Actions", ADDONLIBRARY_TEXTDOMAIN),
		"less_actions"=>__("Less Actions", ADDONLIBRARY_TEXTDOMAIN),
		"hidden_row"=>__("Hidden Row", ADDONLIBRARY_TEXTDOMAIN),
);

$filepathProviderClientText = GlobalsUC::$pathProvider."provider_client_text.php";

if(file_exists($filepathProviderClientText))
	require $filepathProviderClientText;
